export enum ActionTypes {
  LOAD_NOTES = '[Notes] Load notes',
  LOAD_NOTES_SUCCESS = '[Notes] Load notes succes',
  LOAD_NOTES_FAILURE = '[Notes] Load notes failure',
  DELETE_NOTE = '[Notes] Delete note',
  DELETE_NOTE_SUCCESS = '[Notes] Delete note succes',
  DELETE_NOTE_FAILURE = '[Notes] Delete note failure',
  UPDATE_NOTE = '[Notes] Update note',
  UPDATE_NOTE_SUCCESS = '[Notes] Update note succes',
  UPDATE_NOTE_FAILURE = '[Notes] Update note failure',
  CREATE_NOTE = '[Notes] Create note',
  CREATE_NOTE_SUCCESS = '[Notes] Create note succes',
  CREATE_NOTE_FAILURE = '[Notes] Create note failure',
  SELECT_NOTE = '[Notes] Select note',
}
